### ISSUE TITLE
Data Frame Visualization Bug of Integrate Data Example

### ISSUE THREAD

**Issue by RomanIlchenko1308** [pyvista/pyvista#3728]
### Data Frame Visualization Bug
-------------------------------------

Good afternoon everybody,

During the Pyvista Examples investigation in [Integrate Data Example](https://docs.pyvista.org/examples/01-filter/integrate-data.html) I found a tiny bug in the data frame visualization.

![image](https://user-images.githubusercontent.com/44849889/208422367-4ca707d7-3337-4cee-990c-f7be6853f23b.png)

### After a quick review
---------------------------
 I figured out that the issue could be in the CSS class `.rendered_html table` of the ` table-layout: fixed;` property:

![image](https://user-images.githubusercontent.com/44849889/208424410-638aa02f-43e2-4283-963f-6f4b674e8d6e.png)

```CSS
  .rendered_html table {
      margin-left: auto;
      margin-right: auto;
      border: none;
      border-collapse: collapse;
      border-spacing: 0;
      color: var(--sg-text-color);
      font-size: 12px;
      table-layout: fixed;
  }
```

### Probabale Solution
--------------------------

- Change `table-layout: fixed;` ->  `table-layout: auto;`

**Helpful information:**
[table-layout CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout)

![image](https://user-images.githubusercontent.com/44849889/208425192-5a3caa39-a56c-4b69-9f83-2180f323058e.png)

I hope, I could help you a little bit,
with best regards, 
Roman Ilchenko

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Mon Dec 19 13:30:55 2022 W. Europe Standard Time

                OS : Windows
            CPU(s) : 12
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) Iris(R) Xe Graphics
       GPU Version : 4.5.0 - Build 31.0.101.3616

  Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64
  bit (AMD64)]

           pyvista : 0.37.0
               vtk : 9.2.2
             numpy : 1.23.4
           imageio : 2.23.0
            scooby : 0.7.0
             pooch : v1.6.0
        matplotlib : 3.6.2
--------------------------------------------------------------------------------

Process finished with exit code 0
```
