### ISSUE TITLE
Testing against all versions of VTK>8.1.0

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#657]
We need to change the testing pipeline to test PyVista against version 8.1.0-9.x of VTK which are all available on the conda-forge channel: https://anaconda.org/conda-forge/vtk/files

*Why?* Changes are happening across VTK versions that directly affect PyVista and we need to make sure that PyVista is compatible with the VTK version on PyPI (8.1.2) and the latest versions of VTK (8.2 and 9.xdev). #654 is an example of what can go wrong.

*Urgency?* This needs to be implemented before any further "significant" changes to PyVista.

*How?* We should have a pipeline that tests 8.1.0-9.x using anaconda as the package manager as well as have a build that tests 8.1.0-8.1.2 using the wheels on PyPI

Pinging @JevinJ and @akaszynski

**Comment by akaszynski** [comment]
I'll implement the pipeline in Azure.  Tests are already quite long, what do you think about just adding a test matrix of the core API for conda?

**Comment by imsodin** [comment]
I'd suggest only testing for the most recent patch release respectively, i.e. 8.0.1, 8.1.2 and 8.2.0 but not e.g. 8.0.0 or 8.1.1 - there's no good reason to run un-patched packages.

**Comment by akaszynski** [comment]
> I'd suggest only testing for the most recent patch release respectively, i.e. 8.0.1, 8.1.2 and 8.2.0 but not e.g. 8.0.0 or 8.1.1 - there's no good reason to run un-patched packages.

That sounds fair.  That would make only `8.1.1` and `8.2.0` the only ones we'd test according to [anaconda - vtk](https://anaconda.org/anaconda/vtk/files).

**Comment by JevinJ** [comment]
Anything I can do?

**Comment by akaszynski** [comment]
@JevinJ, not at the moment.  I'd continue with the refactor you started.  If you want a break from that, we've got a ton of other PRs that have gone a bit stale and I'd like them to be merged or closed.

**Comment by akaszynski** [comment]
That is, unless you want experience playing around with it.  @JevinJ, if you want to take a stab at it, edit `azure-pipelines.yaml` and add in a new job that uses conda.  Start by adding:

```
# DESCRIPTION: Core API and doc string testing for Linux
- job: Linux_conda
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    DISPLAY: ':99.0'
    PYVISTA_OFF_SCREEN: 'True'

  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
```

From there, add a new task:
```
- script: conda env create --quiet --file environment.yml
  displayName: Create Anaconda environment
```
I've not tested this, so see https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=ubuntu-16-04 for more details.

For the remainder, duplicate the remaining tasks up to and including "Test Core API".

And if you're up for more pain, do the same thing for Windows and MacOS.

This is all assuming you're a sadist and enjoy CI.
